---

- name: copying wrapper script for development
  template:
    src: "{{ role_path }}/files/grav_dev.sh"
    dest: "/opt/grav_dev_{{ grav_site_name }}.sh"
    mode: 0775
  become: true
  when: "grav_sass_src != false"

# 'creates' doesn't really work in install module
- name: "[checking whether wellington exe exists]"
  stat:
    path: "~/.local/bin/wt"
  register: wt_exe

- name: installing wellington sass compiler
  install:
    pkg_mgr: unarchive
    packages:
      - wellington:
          src: https://github.com/wellington/wellington/releases/download/v1.0.4/wt_v1.0.4_linux_amd64.tar.gz
          dest: "~/.local/bin"
          creates: "~/.local/bin/wt"
          mode: "0775"
  when: "grav_sass_src != false and not wt_exe.stat.exists"

- name: installing wellington systemd service
  include_role:
    name: tumf.systemd-service
  vars:
    systemd_service_name: "wellington_{{ grav_site_name }}"
    systemd_service_Unit_Description: "{{ grav_site_name }} wellington sass/scss pre-compilation service"
    systemd_service_Install_WantedBy: multi-user.target
    systemd_service_Service_Restart: always
    systemd_service_Service_User: "{{ freckle_owner }}"
    # systemd_service_Service_Group: "{{ freckle_folder_vars.group | default(omit) }}" --> can't use omit filter in include_role :-(
    systemd_service_Service_WorkingDirectory: "{{ freckle_path }}"
    systemd_service_Service_ExecStart: "/opt/grav_dev_{{ grav_site_name }}.sh"
    systemd_service_Service_Type: "simple"
  become: true

- name: "enable and start wellington sass/scss pre-compile service"
  service:
    name: "wellington_{{ grav_site_name }}"
    enabled: yes
    state: started
  become: true
