- name: "[starting nginx role]"
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts: []
    php_fpm_pool_user: "{{ grav_owner }}"
    nginx_user: "{{ grav_owner }}"
  become: true

- name: "[starting php role]"
  include_role:
    name: geerlingguy.php
  vars:
    php_enable_php_fpm: true
    php_fpm_pool_user: "{{ grav_owner }}"
    php_packages_extra:
      - php-zip
    php_webserver_daemon: "nginx"
  become: true

- name: copying docker run file
  copy:
    src: "{{ role_path }}/files/docker_run.sh"
    dest: /opt/docker_run.sh
    mode: 0775
  become: true
  when: grav_add_docker_run_wrapper
