---
# tasks file for grav

- name: including prepare-folders tasks
  include_tasks: prepare-folders.yml

- name: including site-install tasks
  include_tasks: setup-webserver.yml

- name: including tasks to setup development environment
  include_tasks: dev.yml
  when: grav_dev

# - name: including site-install tasks
  # include_tasks: misc.yml

- name: including docker-specific tasks
  include_tasks: grav_docker.yml
  when: grav_docker
