---
# tasks file for grav

- name: "including nginx & php install tasks"
  include_tasks: install.yml

- name: including prepare-folders tasks
  include_tasks: prepare-folders.yml

- name: including site-install tasks
  include_tasks: setup-site.yml

- name: including misc tasks
  include_tasks: misc.yml






# # changing permissions according to: https://learn.getgrav.org/troubleshooting/permissions
# # takes too long to do it one by one
# - name: changing file permissions
#   shell: "find {{ grav_user_dir_expanded }} -type f | xargs chmod 664"
#   when: "grav_change_user_dir_group_permissions"
#   become: true

# - name: changing grav group ownership
#   file:
#   args:
#     dest: "{{ grav_user_dir_expanded }}"
#     group: "{{ grav_group }}"
#     recurse: yes
#   become: true
#   when: "grav_change_user_dir_group_permissions and grav_group is defined"

# - name: changing directory permissions
#   shell: "find {{ grav_user_dir_expanded }} -type d | xargs chmod 0775"
#   when: "grav_change_user_dir_group_permissions"
#   become: true

# - name: changing directory setguid
#   shell: "find {{ grav_user_dir_expanded }} -type d | xargs chmod +s"
#   when: "grav_change_user_dir_group_permissions"
#   become: true


# - name: install supervisord
#   install:
#     packages;
#       - supervisor
#   when: use_supervisord

# # - name: start php service with supervisord
#   # supervisorctl:
