---
# tasks file for grav

- name: including prepare-folders tasks
  include_tasks: prepare-folders.yml

- name: including site-install tasks
  include_tasks: setup-webserver.yml

- name: including site-install tasks
  include_tasks: misc.yml
