---
- name: "[stopping nginx if running]"
  service:
    name: nginx
    state: stopped
  become: true
  when: "grav_letsencrypt_email is defined and grav_letsencrypt_email"

- name: "managing https certificate for {{ grav_domain }}"
  include_role:
    name: thefinn93.letsencrypt
  vars:
    letsencrypt_email: "{{ grav_letsencrypt_email }}"
    letsencrypt_cert_comains:
      - "{{ grav_domain }}"
    letsencrypt_webroot_path: "{{ grav_app_path }}"
    letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
  when: "grav_letsencrypt_email is defined and grav_letsencrypt_email"

- name: "[start nginx if exists]"
  service:
    name: nginx
    state: started
  become: true
  when: "grav_letsencrypt_email is defined and grav_letsencrypt_email"

- name: restarting nginx webserver
  service:
  args:
    state: restarted
    name: "nginx"
  become: true
  when: "grav_letsencrypt_email is not defined or not grav_letsencrypt_email"
