# tasks to install a grav site
- name: ensuring sites-available folder exists
  file:
    path: "/etc/nginx/sites-available"
    owner: "root"
    recurse: yes
  become: yes

- name: ensuring sites-enabled folder exists
  file:
    path: "/etc/nginx/sites-enabled"
    owner: "root"
    recurse: yes
  become: yes


- name: copying nginx.conf
  copy:
  args:
    src: "{{ grav_app_path }}/webserver-configs/nginx.conf"
    force: no
    group: root
    owner: root
    remote_src: yes
    dest: "/etc/nginx/sites-available/{{ grav_site_name }}"
  become: true

- name: linking grav site to sites-enabled
  file:
  args:
    dest: "/etc/nginx/sites-enabled/{{ grav_site_name }}"
    src: "/etc/nginx/sites-available/{{ grav_site_name }}"
    state: link
  become: true

- name: setting web root
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "    root {{ grav_app_path }};"
    regexp: '^\s*root.*;$'
  become: true

- name: removing php-fpm socket config
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    state: absent
    regexp: "fastcgi_pass unix:"
  become: true

- name: setting php-fpm pass config
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "        fastcgi_pass 127.0.0.1:9000;"
    regexp: "fastcgi_pass 127.0.0.1:9000;"
  become: true

- name: "setting listen port to '{{ grav_webserver_port }}'"
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "    listen {{ grav_webserver_port }};"
    regexp: "listen.*;$"
  become: true

# - name: refresh gpm index for site
#   command: bin/gpm  selfupgrade -f
#   args:
#     chdir: "{{ grav_site_dir }}"
#   become_user: "{{ nginx_user }}"
#   become: yes
